language: go
go:
- '1.8'
script:
- make all
- tools/bin/goveralls -coverprofile=cover.out -service=travis-ci
deploy:
  provider: releases
  api_key:
    secure: b3TUPORi3fyjtAlMmpnvNfAUGC/j3A8HfxnPg3nrsu5ZRxBjgijcWXOhgpwMXtwQtPr0dY1qaMeS5ix5QPh2bjpF+im4iiNUnXe2EerEpKTWRsvgp7/4ETtMTgg6mePo/gNfhpPIQEgY4/RX56LmaeBf5z9YYrD+G+B8Ic+/QomAZKaJZHYv8KV68eeNgXQFMAGDz+sgjeEcVKUoUGAA3gWjiTjDAdNG3BQHN2d10m3Zr21j3XrKg6UDHpHDIYyZOOqjqYF+a/fKa23hKGuBeulYuYcEidEynQITIeaVDl6/mRfb3pa3Ui2pqG5CpChvUjfQ0K5BKoM7RuvQH/CL7223pOpbRYIk4NoNI/vGHRc9LcEkD5OmgYIuD1hmOSDESbIg+tC12Jk+DmTOUx/ObU5vWBNQCGssbC/j0Bzw3yK1v+Q66rwU1m7LcMR/QXMJynLI3GzLxaExLQM5osYYg1JA6p3t2U4EdmWFRTOuh8yHb4Vs0NUcPPX5j3sxK+h+VkFaTC/G4Rc5drA4uO1cG6R60ac6Du2AT+r5E18p3G0J6CZQPe1uS0A1DTgONQBmRUdEa9Z82TlpKgVKCbZDWlneVRW3SEMn/aY93OfwLN8WF5msJ/4V/hi1dYq1mqJaHmy+MAqey+l0OE7OAdsjCrVuNiESgZdzZ+Xr/wy6Zww=
  file: makecerts.x86_64
  on:
    repo: wrouesnel/makecerts
    tags: true
    branch: master
